on:
  github:
    branches:
      only: main

jobs:

  cloneRepo:
    resources:
      instance-type: P4000
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/NLP-Text-Generation
      url: context.event.github.url
      ref: context.event.github.ref
    

  generateText:
    resources:
      instance-type: P4000
    needs:
      - cloneRepo
    inputs:
      repo: cloneRepo.outputs.repo
    outputs:
      generatedText:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run
        curl -fsSL https://code-server.dev/install.sh | sh
        timeout 2s code-server
        cd ~/.config/code-server
        cat config.yaml
        npm install -g localtunnel
        code-server --bind-addr 127.0.0.1:8040  & lt --port 8040
      image: paperspace/transformers-gpu:0.3.0
